version: '3.9'
services:
  pgdb_server:
    image: postgres:13.2
    restart: always
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
    ports:
      - "5432:5432"
    volumes:
      - /home/y_n_vdrlinden/postgres_data:/var/lib/postgresql/data
  db_admin:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  api_gateway:
    image: devopsfaith/krakend:1.3
    container_name: api_gateway_ct_name
    volumes:
      - ./krakend:/etc/krakend/
    ports:
      - "8081:8081"
  account_service:
    build:
      context: ./account_microservice
    container_name: account_microservice_ct_name
    environment:
      #Check if we need .db
      - DB_URL=postgresql://testuser:testpass@pgdb_server:5432/account.db
    depends_on:
      - pgdb_server
    ports:
      - "5000:5000"
  cart_service:
    build:
      context: ./cart_microservice
    container_name: cart_microservice_ct_name
    environment:
      - DB_URL=postgresql://testuser:testpass@pgdb_server:5432/cart.db
    depends_on:
      - pgdb_server
    ports:
      - "5001:5000"
  product_service:
    build:
      context: ./product_microservice
    environment:
      - DB_URL=postgresql://testuser:testpass@pgdb_server:5432/product.db
    depends_on:
      - pgdb_server
    ports:
      - "5002:5000"
#  recommender_service:
#    build:
#      context: ./recommender_microservice
#    # IF WE WANT TO USE DATBASE WITH COMPOSERS UNCOMMENT BELOW!!!
#    # environment:
#    #   - DB_URL=postgresql://testuser:testpass@pgdb_server:5432/place
#    # depends_on:
#    #   - pgdb_server
#    ports:
#      - "5003:5000"