version: '3.9'
services:
  pgdb_server:
    image: postgres:13.2
    restart: always
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
    ports:
      - "5432:5432"
    volumes:
      # - /home/y_n_vdrlinden/postgres_data:/var/lib/postgresql/data
      - /home/t_ghorbandi/postgres_data:/var/lib/postgresql/data
  db_admin:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  api_gateway:
    image: devopsfaith/krakend:1.3
    container_name: api_gateway_ct
    volumes:
      - ./krakend:/etc/krakend/
    ports:
      - "8081:8081"
  account_service:
    build:
      context: ./account_microservice
    container_name: account_microservice_ct
    environment:
      - DB_URL=postgresql://testuser:testpass@pgdb_server:5432/account.db
    depends_on:
      - pgdb_server
    ports:
      - "5000:5000"
  cart_service:
    build:
      context: ./cart_microservice
    container_name: cart_microservice_ct
    environment:
      - DB_URL=postgresql://testuser:testpass@pgdb_server:5432/cart.db
    depends_on:
      - pgdb_server
    ports:
      - "5001:5000"
  product_service:
    build:
      context: ./product_microservice
    container_name: product_microservice_ct
    environment:
      - DB_URL=postgresql://testuser:testpass@pgdb_server:5432/product.db
    depends_on:
      - pgdb_server
    ports:
      - "5002:5000"